---
- name: "Sicurezza Attiva: Ban IP Malizioso"
  hosts: "{{ target_ip | default('all') }}"
  become: yes

  tasks:
    - debug:
      var: attacker_ip
    - name: "Registra l'azione nel log di sistema locale"
      syslogger:
        msg: "WAZUH-ACTIVE-RESPONSE: Bannato IP {{ attacker_ip }} su richiesta del Manager"
        priority: "err"
        facility: "auth"
